# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User

    fos_user.registration_subscriber:
      class: AppBundle\EventListener\FosUserListener
      tags:
          - { name: kernel.event_subscriber }

    app.crud_subscriber:
      class: AppBundle\EventListener\FosUserListener
      arguments: ["security.token_storage"]
      tags:
          - { name: kernel.event_subscriber }

    app.elasticsearch.finder:
      class: AppBundle\Elasticsearch\Finder
      arguments: ["@service_container"]
