# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - AppBundle\Entity\User
    grant_type.api_key:
        class: AppBundle\OAuth\ApiKeyGrantExtension
        tags:
            -  { name: fos_oauth_server.grant_extension, uri: 'http://%domain%/grants/api_key' }
        arguments: ["@user_repository", "@security.encoder_factory"]
    fos_user.registration_subscriber:
      class: AppBundle\EventListener\FosUserListener
      tags:
          - { name: kernel.event_subscriber }
