fos_user:
    db_driver: orm
    firewall_name: api
    user_class: AppBundle\Entity\User
    registration:
        form:
            validation_groups: [TacticRegistration]
    profile:
        form:
            validation_groups: [TacticProfile]
