#FILTERS
services:
  form.type.users_filter:
      class: AppBundle\Form\Type\Filter\UserFilterType
      tags:
          - { name: form.type, alias: user_filter }
  provider.users_filter:
      class: AppBundle\Filter\UserFilterProvider
      parent: vardius_list.filter.provider

  form.type.files_filter:
      class: AppBundle\Form\Type\Filter\FileFilterType
      tags:
          - { name: form.type, alias: file_filter }
  provider.files_filter:
      class: AppBundle\Filter\FileFilterProvider
      parent: vardius_list.filter.provider

  form.type.tags_filter:
      class: AppBundle\Form\Type\Filter\TagFilterType
      tags:
          - { name: form.type, alias: tag_filter }
  provider.tags_filter:
      class: AppBundle\Filter\TagFilterProvider
      parent: vardius_list.filter.provider

  form.type.skills_filter:
      class: AppBundle\Form\Type\Filter\SkillFilterType
      tags:
          - { name: form.type, alias: skill_filter }
  provider.skills_filter:
      class: AppBundle\Filter\SkillFilterProvider
      parent: vardius_list.filter.provider

  form.type.jobs_filter:
      class: AppBundle\Form\Type\Filter\JobFilterType
      tags:
          - { name: form.type, alias: job_filter }
  provider.jobs_filter:
      class: AppBundle\Filter\JobFilterProvider
      parent: vardius_list.filter.provider

  form.type.social_medias_filter:
      class: AppBundle\Form\Type\Filter\SocialMediaFilterType
      tags:
          - { name: form.type, alias: social_media_filter }
  provider.social_medias_filter:
      class: AppBundle\Filter\SocialMediaFilterProvider
      parent: vardius_list.filter.provider

  form.type.icons_filter:
      class: AppBundle\Form\Type\Filter\IconFilterType
      tags:
          - { name: form.type, alias: icon_filter }
  provider.icons_filter:
      class: AppBundle\Filter\IconFilterProvider
      parent: vardius_list.filter.provider