#LIST VIEWS
services:
  users.list_view:
    class: AppBundle\ListView\UserListViewProvider
    parent: vardius_list.list_view.provider

  articles.list_view:
    class: AppBundle\ListView\ArticleListViewProvider
    parent: vardius_list.list_view.provider

  categories.list_view:
    class: AppBundle\ListView\CategoryListViewProvider
    parent: vardius_list.list_view.provider

  tags.list_view:
    class: AppBundle\ListView\TagListViewProvider
    parent: vardius_list.list_view.provider