#LIST VIEWS
services:
  users.list_view:
    class: AppBundle\ListView\UserListViewProvider
    parent: vardius_list.list_view.provider

  files.list_view:
    class: AppBundle\ListView\FileListViewProvider
    parent: vardius_list.list_view.provider

  tags.list_view:
    class: AppBundle\ListView\TagListViewProvider
    parent: vardius_list.list_view.provider

  projects.list_view:
    class: AppBundle\ListView\ProjectListViewProvider
    parent: vardius_list.list_view.provider

  skills.list_view:
    class: AppBundle\ListView\SkillListViewProvider
    parent: vardius_list.list_view.provider

  project_skills.list_view:
      class: AppBundle\ListView\ProjectSkillListViewProvider
      parent: vardius_list.list_view.provider

  jobs.list_view:
    class: AppBundle\ListView\JobListViewProvider
    parent: vardius_list.list_view.provider

  social_medias.list_view:
    class: AppBundle\ListView\SocialMediaListViewProvider
    parent: vardius_list.list_view.provider

  icons.list_view:
    class: AppBundle\ListView\IconListViewProvider
    parent: vardius_list.list_view.provider

  categories.list_view:
    class: AppBundle\ListView\CategoryListViewProvider
    parent: vardius_list.list_view.provider

  articles.list_view:
    class: AppBundle\ListView\ArticleListViewProvider
    parent: vardius_list.list_view.provider